plugins { id "com.android.application" }

android {
    namespace "hu.omegacode.ensa.offlinedemo"
    compileSdk 36

    defaultConfig {
        applicationId "hu.omegacode.ensa.offlinedemo"
        minSdk 23
        targetSdk 36
        versionCode 44
        versionName "0.4.4"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}
