"""fix password length

Revision ID: 87874fa13918
Revises: a9c1747f33ff
Create Date: 2025-11-13 20:18:16.358824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87874fa13918'
down_revision: Union[str, Sequence[str], None] = 'a9c1747f33ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
