"""add_new_column

Revision ID: 93e052862ab7
Revises: 87874fa13918
Create Date: 2025-11-19 07:21:58.444051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93e052862ab7'
down_revision: Union[str, Sequence[str], None] = '87874fa13918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_gorup_members_group'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'user_groups', ['group_id'], ['id'])
    op.alter_column('skills', 'skill_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'skills', ['skill_name'])
    op.alter_column('user_groups', 'group_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_groups_id'), table_name='user_groups')
    op.create_index(op.f('ix_user_groups_id'), 'user_groups', ['id'], unique=False)
    op.alter_column('user_skills', 'skill_level',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('specialty', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialty')
    op.alter_column('user_skills', 'skill_level',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_groups_id'), table_name='user_groups')
    op.create_index(op.f('ix_groups_id'), 'user_groups', ['id'], unique=False)
    op.alter_column('user_groups', 'group_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'skills', type_='unique')
    op.alter_column('skills', 'skill_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gorup_members_group'), 'group_members', 'user_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
