plugins { id 'com.android.application' }

android {
    namespace 'hu.babatamogatas.app'
    compileSdk 35

    defaultConfig {
        applicationId 'hu.babatamogatas.app'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.4.0'
    }

    buildTypes {
        debug { applicationIdSuffix '.debug' }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
